export const restURL = 'https://rest.bitcoin.com/v2/';
export const tokenBaseUrl = 'https://tokens.bch.sx/64';
export const cashExplorer = 'https://cashexplorer.bitcoin.com';
export const slpDBUrl = 'https://nyc1.slpdb.io/q';
export const slpDBUrl2 = 'https://slpdb.fountainhead.cash/q'; // SLP block height
export const bitDBUrl = 'https://bitdb.bch.sx/q';
export const slpSocketUrl = 'https://nyc1.slpdb.io/s';
// export const slpSocketUrl = 'https://slpsocket.fountainhead.cash/s';
export const bitSocketUrl = 'https://bitdb.bch.sx/s';
